// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {vpn} from '../models';

export function Connect():Promise<vpn.Status>;

export function Disconnect():Promise<vpn.Status>;

export function ExampleConfig():Promise<string>;

export function LoadConfig(arg1:string,arg2:string):Promise<Record<string, any>>;

export function LoadConfigFromFile(arg1:string):Promise<Record<string, any>>;

export function Status():Promise<vpn.Status>;
