// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect() {
  return window['go']['main']['App']['Connect']();
}

export function Disconnect() {
  return window['go']['main']['App']['Disconnect']();
}

export function ExampleConfig() {
  return window['go']['main']['App']['ExampleConfig']();
}

export function LoadConfig(arg1, arg2) {
  return window['go']['main']['App']['LoadConfig'](arg1, arg2);
}

export function LoadConfigFromFile(arg1) {
  return window['go']['main']['App']['LoadConfigFromFile'](arg1);
}

export function Status() {
  return window['go']['main']['App']['Status']();
}
